### ISSUE TITLE
ModuleNotFoundError: No module named '_ctypes' error when run pytriton server with 0.5.0

### ISSUE THREAD

**Issue by lionsheep0724** [triton-inference-server/pytriton#56]
**Description**

I got an error ModuleNotFoundError: No module named '_ctypes'  when I run pytriton server.
The code and env are exactly same with last run, which has no problem (0.4.2)

**To reproduce**

If relevant, add a minimal example so that we can reproduce the error, if necessary, by running the code. For example:

```python
# server
from pytriton.decorators import batch
from pytriton.model_config import ModelConfig, Tensor
from pytriton.triton import Triton

@batch
def infer_fn(**inputs: np.ndarray):
    (audio_feature,) = inputs.values()

    # convert to cuda
    audio_feature_tensor: torch.Tensor = torch.from_numpy(audio_feature).to("cuda:0")
    # generate token
    token: torch.Tensor = whisper_model.generate_token(input_features=audio_feature_tensor)
    token: np.ndarray = token.cpu().numpy()

    return {"token": token}


with Triton(
        config=TritonConfig(http_port=args.http_port, grpc_port=args.grpc_port, metrics_port=args.metrics_port)
    ) as triton:
        logger.info(f"Loading STT model with batch size : {MAX_BATCH_SIZE}")
        triton.bind(
            model_name="Whisper",
            infer_func=infer_fn,
            inputs=[
                Tensor(name="audio_feature", dtype=np.float32, shape=(80, 3000)),
            ],
            outputs=[
                Tensor(name="token", dtype=np.int64, shape=(-1,)),
            ],
            config=ModelConfig(max_batch_size=MAX_BATCH_SIZE),
            strict=True,
        )
        logger.info("Serving inference")
        triton.serve()
        logger.info("Pytriton is ready")
```

**Observed results and expected behavior**

Refer to error log below.
```
2024-01-17 21:10:18 Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-01-17 21:10:34 2024-01-17 21:10:34,975 - INFO - pytriton.triton: Read more about configuring and serving models in documentation: https://triton-inference-server.github.io/pytriton.
2024-01-17 21:10:34 2024-01-17 21:10:34,975 - INFO - pytriton.triton: (Press CTRL+C or use the command `kill -SIGINT 1` to send a SIGINT signal and quit)
2024-01-17 21:10:34 2024-01-17 21:10:34,975 - INFO - pytriton_single_pipeline: Loading STT model with batch size : 1
2024-01-17 21:10:38 I0117 12:10:34.336323 38 pinned_memory_manager.cc:241] Pinned memory pool is created at '0x304600000' with size 268435456
2024-01-17 21:10:38 I0117 12:10:34.336439 38 cuda_memory_manager.cc:107] CUDA memory pool is created on device 0 with size 67108864
2024-01-17 21:10:38 I0117 12:10:34.341477 38 server.cc:606] 
2024-01-17 21:10:38 +------------------+------+
2024-01-17 21:10:38 | Repository Agent | Path |
2024-01-17 21:10:38 +------------------+------+
2024-01-17 21:10:38 +------------------+------+
2024-01-17 21:10:38 
2024-01-17 21:10:38 I0117 12:10:34.341506 38 server.cc:633] 
2024-01-17 21:10:38 +---------+------+--------+
2024-01-17 21:10:38 | Backend | Path | Config |
2024-01-17 21:10:38 +---------+------+--------+
2024-01-17 21:10:38 +---------+------+--------+
2024-01-17 21:10:38 
2024-01-17 21:10:38 I0117 12:10:34.341527 38 server.cc:676] 
2024-01-17 21:10:38 +-------+---------+--------+
2024-01-17 21:10:38 | Model | Version | Status |
2024-01-17 21:10:38 +-------+---------+--------+
2024-01-17 21:10:38 +-------+---------+--------+
2024-01-17 21:10:38 
2024-01-17 21:10:38 I0117 12:10:34.379326 38 metrics.cc:817] Collecting metrics for GPU 0: NVIDIA RTX A2000 8GB Laptop GPU
2024-01-17 21:10:38 I0117 12:10:34.385456 38 metrics.cc:710] Collecting CPU metrics
2024-01-17 21:10:38 I0117 12:10:34.385609 38 tritonserver.cc:2483] 
2024-01-17 21:10:38 +----------------------------------+------------------------------------------+
2024-01-17 21:10:38 | Option                           | Value                                    |
2024-01-17 21:10:38 +----------------------------------+------------------------------------------+
2024-01-17 21:10:38 | server_id                        | triton                                   |
2024-01-17 21:10:38 | server_version                   | 2.41.0                                   |
2024-01-17 21:10:38 | server_extensions                | classification sequence model_repository |
2024-01-17 21:10:38 |                                  |  model_repository(unload_dependents) sch |
2024-01-17 21:10:38 |                                  | edule_policy model_configuration system_ |
2024-01-17 21:10:38 |                                  | shared_memory cuda_shared_memory binary_ |
2024-01-17 21:10:38 |                                  | tensor_data parameters statistics trace  |
2024-01-17 21:10:38 |                                  | logging                                  |
2024-01-17 21:10:38 | model_repository_path[0]         | /root/.cache/pytriton/workspace_ofhp5n85 |
2024-01-17 21:10:38 | model_control_mode               | MODE_EXPLICIT                            |
2024-01-17 21:10:38 | strict_model_config              | 0                                        |
2024-01-17 21:10:38 | rate_limit                       | OFF                                      |
2024-01-17 21:10:38 | pinned_memory_pool_byte_size     | 268435456                                |
2024-01-17 21:10:38 | cuda_memory_pool_byte_size{0}    | 67108864                                 |
2024-01-17 21:10:38 | min_supported_compute_capability | 6.0                                      |
2024-01-17 21:10:38 | strict_readiness                 | 1                                        |
2024-01-17 21:10:38 | exit_timeout                     | 30                                       |
2024-01-17 21:10:38 | cache_enabled                    | 0                                        |
2024-01-17 21:10:38 +----------------------------------+------------------------------------------+
2024-01-17 21:10:38 
2024-01-17 21:10:38 I0117 12:10:34.387048 38 grpc_server.cc:2495] Started GRPCInferenceService at 0.0.0.0:8001
2024-01-17 21:10:38 I0117 12:10:34.387252 38 http_server.cc:4619] Started HTTPService at 0.0.0.0:10100
2024-01-17 21:10:38 I0117 12:10:34.429670 38 http_server.cc:282] Started Metrics Service at 0.0.0.0:8002
2024-01-17 21:10:38 I0117 12:10:34.987339 38 model_lifecycle.cc:461] loading: Whisper:1
2024-01-17 21:10:38 I0117 12:10:36.247956 38 python_be.cc:2363] TRITONBACKEND_ModelInstanceInitialize: Whisper_0_0 (CPU device 0)
2024-01-17 21:10:38 Traceback (most recent call last):
2024-01-17 21:10:38   File "<string>", line 1, in <module>
2024-01-17 21:10:38   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
2024-01-17 21:10:38     exitcode = _main(fd, parent_sentinel)
2024-01-17 21:10:38   File "/usr/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
2024-01-17 21:10:38     self = reduction.pickle.load(from_parent)
2024-01-17 21:10:38   File "/tmp/folderSrr2Ia/1/data.py", line 21, in <module>
2024-01-17 21:10:38     import ctypes
2024-01-17 21:10:38   File "/usr/lib/python3.8/ctypes/__init__.py", line 7, in <module>
2024-01-17 21:10:38     from _ctypes import Union, Structure, Array
2024-01-17 21:10:38 ModuleNotFoundError: No module named '_ctypes'
2024-01-17 21:10:38 I0117 12:10:36.426031 38 pb_stub.cc:346] Failed to initialize Python stub: TritonModelException: Model initialize error: Traceback (most recent call last):
2024-01-17 21:10:38   File "/tmp/folderSrr2Ia/1/model.py", line 392, in initialize
2024-01-17 21:10:38     self._serializer_deserializer.start(data_socket)
2024-01-17 21:10:38   File "/tmp/folderSrr2Ia/1/data.py", line 952, in start
2024-01-17 21:10:38     self._tensor_store.start()
2024-01-17 21:10:38   File "/tmp/folderSrr2Ia/1/data.py", line 555, in start
2024-01-17 21:10:38     self._remote_blocks_store_manager.start()
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/managers.py", line 583, in start
2024-01-17 21:10:38     self._address = reader.recv()
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
2024-01-17 21:10:38     buf = self._recv_bytes()
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
2024-01-17 21:10:38     buf = self._recv(4)
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
2024-01-17 21:10:38     raise EOFError
2024-01-17 21:10:38 EOFError
2024-01-17 21:10:38 
2024-01-17 21:10:38 
2024-01-17 21:10:38 At:
2024-01-17 21:10:38   /tmp/folderSrr2Ia/1/model.py(426): initialize
2024-01-17 21:10:38 
2024-01-17 21:10:38 E0117 12:10:36.600638 38 backend_model.cc:635] ERROR: Failed to create instance: TritonModelException: Model initialize error: Traceback (most recent call last):
2024-01-17 21:10:38   File "/tmp/folderSrr2Ia/1/model.py", line 392, in initialize
2024-01-17 21:10:38     self._serializer_deserializer.start(data_socket)
2024-01-17 21:10:38   File "/tmp/folderSrr2Ia/1/data.py", line 952, in start
2024-01-17 21:10:38     self._tensor_store.start()
2024-01-17 21:10:38   File "/tmp/folderSrr2Ia/1/data.py", line 555, in start
2024-01-17 21:10:38     self._remote_blocks_store_manager.start()
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/managers.py", line 583, in start
2024-01-17 21:10:38     self._address = reader.recv()
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
2024-01-17 21:10:38     buf = self._recv_bytes()
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
2024-01-17 21:10:38     buf = self._recv(4)
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
2024-01-17 21:10:38     raise EOFError
2024-01-17 21:10:38 EOFError
2024-01-17 21:10:38 
2024-01-17 21:10:38 
2024-01-17 21:10:38 At:
2024-01-17 21:10:38   /tmp/folderSrr2Ia/1/model.py(426): initialize
2024-01-17 21:10:38 
2024-01-17 21:10:38 E0117 12:10:36.600727 38 model_lifecycle.cc:621] failed to load 'Whisper' version 1: Internal: TritonModelException: Model initialize error: Traceback (most recent call last):
2024-01-17 21:10:38   File "/tmp/folderSrr2Ia/1/model.py", line 392, in initialize
2024-01-17 21:10:38     self._serializer_deserializer.start(data_socket)
2024-01-17 21:10:38   File "/tmp/folderSrr2Ia/1/data.py", line 952, in start
2024-01-17 21:10:38     self._tensor_store.start()
2024-01-17 21:10:38   File "/tmp/folderSrr2Ia/1/data.py", line 555, in start
2024-01-17 21:10:38     self._remote_blocks_store_manager.start()
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/managers.py", line 583, in start
2024-01-17 21:10:38     self._address = reader.recv()
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
2024-01-17 21:10:38     buf = self._recv_bytes()
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
2024-01-17 21:10:38     buf = self._recv(4)
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
2024-01-17 21:10:38     raise EOFError
2024-01-17 21:10:38 EOFError
2024-01-17 21:10:38 
2024-01-17 21:10:38 
2024-01-17 21:10:38 At:
2024-01-17 21:10:38   /tmp/folderSrr2Ia/1/model.py(426): initialize
2024-01-17 21:10:38 
2024-01-17 21:10:38 I0117 12:10:36.600752 38 model_lifecycle.cc:756] failed to load 'Whisper'
2024-01-17 21:10:38 Signal (2) received.
2024-01-17 21:10:38 I0117 12:10:36.601623 38 server.cc:307] Waiting for in-flight requests to complete.
2024-01-17 21:10:38 Traceback (most recent call last):
2024-01-17 21:10:38   File "inference_pipeline.py", line 126, in <module>
2024-01-17 21:10:38     main()
2024-01-17 21:10:38   File "inference_pipeline.py", line 102, in main
2024-01-17 21:10:38     triton.bind(
2024-01-17 21:10:38   File "/usr/local/lib/python3.8/dist-packages/pytriton/triton.py", line 389, in bind
2024-01-17 21:10:38     self._model_manager.add_model(model, self.is_connected())
2024-01-17 21:10:38   File "/usr/local/lib/python3.8/dist-packages/pytriton/models/manager.py", line 78, in add_model
2024-01-17 21:10:38     self._load_model(model)
2024-01-17 21:10:38   File "/usr/local/lib/python3.8/dist-packages/pytriton/models/manager.py", line 127, in _load_model
2024-01-17 21:10:38     client.load_model(config=config, files=files)
2024-01-17 21:10:38   File "/usr/local/lib/python3.8/dist-packages/pytriton/client/client.py", line 397, in load_model
2024-01-17 21:10:38     self._general_client.load_model(self._model_name, config=config, files=files)
2024-01-17 21:10:38   File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/_client.py", line 663, in load_model
2024-01-17 21:10:38     _raise_if_error(response)
2024-01-17 21:10:38   File "/usr/local/lib/python3.8/dist-packages/tritonclient/http/_utils.py", line 69, in _raise_if_error
2024-01-17 21:10:38     raise error
2024-01-17 21:10:38 tritonclient.utils.InferenceServerException: [400] load failed for model 'Whisper': version 1 is at UNAVAILABLE state: Internal: TritonModelException: Model initialize error: Traceback (most recent call last):
2024-01-17 21:10:38   File "/tmp/folderSrr2Ia/1/model.py", line 392, in initialize
2024-01-17 21:10:38     self._serializer_deserializer.start(data_socket)
2024-01-17 21:10:38   File "/tmp/folderSrr2Ia/1/data.py", line 952, in start
2024-01-17 21:10:38     self._tensor_store.start()
2024-01-17 21:10:38   File "/tmp/folderSrr2Ia/1/data.py", line 555, in start
2024-01-17 21:10:38     self._remote_blocks_store_manager.start()
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/managers.py", line 583, in start
2024-01-17 21:10:38     self._address = reader.recv()
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/connection.py", line 250, in recv
2024-01-17 21:10:38     buf = self._recv_bytes()
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
2024-01-17 21:10:38     buf = self._recv(4)
2024-01-17 21:10:38   File "/usr/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
2024-01-17 21:10:38     raise EOFError
2024-01-17 21:10:38 EOFError
2024-01-17 21:10:38 
2024-01-17 21:10:38 
2024-01-17 21:10:38 At:
2024-01-17 21:10:38   /tmp/folderSrr2Ia/1/model.py(426): initialize
2024-01-17 21:10:38 ;
2024-01-17 21:10:38 
2024-01-17 21:10:38 I0117 12:10:36.601632 38 server.cc:323] Timeout 30: Found 0 model versions that have in-flight inferences
2024-01-17 21:10:38 I0117 12:10:36.601635 38 server.cc:338] All models are stopped, unloading models
2024-01-17 21:10:38 I0117 12:10:36.601636 38 server.cc:345] Timeout 30: Found 0 live models and 0 in-flight non-inference requests
```

**Environment**

- OS/container version: ubuntu, 22.04
- Python interpreter distribution and version: 3.8
- pip version: 23.2.1
- PyTriton version: 0.5.0

Please refer to my dockerfile, as below.
```
# Use Ubuntu 22.04 as base image
FROM ubuntu:22.04

# Install necessary packages
RUN apt update -y && apt install -y --fix-missing software-properties-common

# Add repository with various Python versions
RUN add-apt-repository ppa:deadsnakes/ppa -y

#Set timezone
RUN apt-get update && \
    apt-get install -yq tzdata && \
    ln -fs /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

# Install Python 3.8 and required libraries
RUN apt install -y --fix-missing python3.8 libpython3.8 python3.8-distutils python3-pip \
     build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev \
     libffi-dev curl libbz2-dev pkg-config make


# install dependencies
COPY ./requirements.txt /workspace/requirements.txt
RUN pip install -r  /workspace/requirements.txt

# Install nvidia-pytriton using pip
RUN python3.8 -m pip install nvidia-pytriton
RUN python3.8 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

WORKDIR /workspace

# copy model
COPY ./models /workspace
```

**Additional context**
I don't understand why the error log says ```failed to load 'Whisper' version 1```. The previous version loaded model with version 2, since folder name is 2.

**Comment by lionsheep0724** [comment]
Many thanks to your quick reply.
It sounds to me  there's a compatibility issue with python 3.8, at 0.5.0.
I'm not sure that my env is okay with 3.8, byt I'll try.

P.S : I have question about decoupled model in 0.5.0.
Its [documentation](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/decoupled_models.md) says that it is specifically useful in Automated Speech Recognition (ASR), but I don't understand why. Here's my questions.
1. In my case, real time audio packet transmitted to fastapi server (keep alive connection with http) and the packet converted to audio feature when audio packet is accumulated enough to ASR. (maybe few seconds of packets or more) 
2. And then request to pytriton with extracted feature, get ASR response(text).
3. In my scenario, how can I implement decopled models and whats the point of advantage of it? I wonder if it guarantees inference with ordered-manner, w.r.t each packet channels. I guess the audio packet source and fastapi server should be 1:1, and pytriton server and fastapi server will be 1:N, to handle multiple audio packet source with no audio sources mixed.
4. Does pytriton with decoupled model can handle stream data? i.e. , can wee feed audio packet (bytes) to  server, directly?
5. How can we control the reponse length? (the doc says server deliver response whenever it deems fit)
6. How can we control parallelism? (number of workers, etc..) refer to [doc](https://triton-inference-server.github.io/pytriton/0.5.0/clients/#decoupled-models-and-clients), It can receive many requests in parallel and perform inference on each request independently.

If my question is too broad, it is okay to open a new thread. Feel free to give me questions as my explanation is quite unclear.

**Comment by piotrm-nvidia** [comment]
Please be so kind to create new thread about decoupled models and ASR. Let's focus at Python 3.8 support here.
