### ISSUE TITLE
[Error following Quick Start] - tritonclient.utils.InferenceServerException: [400] client received an empty response from the server.

### ISSUE THREAD

**Issue by sophot** [triton-inference-server/pytriton#76]
**Description**
I was following the code in the Installation & Quick Start page. 
When I run the code, there is a error as mention below.
```python
Traceback (most recent call last):
  File "/workspace/test.py", line 34, in <module>
    with Triton() as triton:
  File "/usr/local/lib/python3.10/dist-packages/pytriton/triton.py", line 695, in __enter__
    super().__enter__()
  File "/usr/local/lib/python3.10/dist-packages/pytriton/triton.py", line 548, in __enter__
    self.connect()
  File "/usr/local/lib/python3.10/dist-packages/pytriton/triton.py", line 480, in connect
    self._wait_for_server()
  File "/usr/local/lib/python3.10/dist-packages/pytriton/triton.py", line 570, in _wait_for_server
    self._log_level_checker.check()
  File "/usr/local/lib/python3.10/dist-packages/pytriton/triton.py", line 351, in check
    self._log_settings = client.get_log_settings()
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_client.py", line 937, in get_log_settings
    _raise_if_error(response)
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/http/_utils.py", line 69, in _raise_if_error
    raise error
tritonclient.utils.InferenceServerException: [400] client received an empty response from the server.
Triton Inference Server exited with failure. Please wait.
```

**To reproduce**

If relevant, add a minimal example so that we can reproduce the error, if necessary, by running the code. For example:

```python
import numpy as np
import torch
from pytriton.decorators import batch
from pytriton.model_config import ModelConfig, Tensor
from pytriton.triton import Triton, TritonConfig

if __name__ == "__main__":
    import torch

    model = torch.nn.Linear(2, 3).to("cuda").eval()

    @batch
    def infer_fn(**inputs: np.ndarray):
        (input1_batch,) = inputs.values()
        input1_batch_tensor = torch.from_numpy(input1_batch).to("cuda")
        output1_batch_tensor = model(input1_batch_tensor) # Calling the Python model inference
        output1_batch = output1_batch_tensor.cpu().detach().numpy()
        return [output1_batch]

    with Triton() as triton:
        triton.bind(
            model_name="Linear",
            infer_func=infer_fn,
            inputs=[
                Tensor(dtype=np.float32, shape=(-1,)),
            ],
            outputs=[
                Tensor(dtype=np.float32, shape=(-1,)),
            ],
            config=ModelConfig(max_batch_size=128)
        )

        triton.serve()
```

**Environment**
- PyTriton is installed using pip.
The code is run in a docker container I got from **'nvcr.io/nvidia/tritonserver:24.03-py3'**.

**Comment by sophot** [comment]
Error resolved when I change the port for http, grpc and metric.

```python
#Before
with Triton() as triton:
...
#After
with Triton(config=TritonConfig(http_port=8015, grpc_port=8016, metrics_port=8017)) as triton:
```
